version: '3.5'
services:
  frontend_service:
    container_name: alianzas-front
    image: alianzas-front
    ports:
      - "8091:80"
    build:
      context: ./alianzas-front
      dockerfile: ./Dockerfile
    networks:
      - network
    volumes: 
      - v_front_dist:/usr/share/nginx/html/alianzas
      - v_front_logs:/var/log
      - v_front_config:/usr/share/nginx/html/alianzas/assets/config/
    restart: always
volumes:
  v_front_dist:
  v_front_config:
  v_front_logs:
networks:
  network:    
        